### ISSUE TITLE
Where is the supplementary material you mentioned?

### ISSUE THREAD

**Issue by Dongj909** [fourson/UnModNet#2]
Dear author,

Hello. This paper has been extremely beneficial to me. However, I have a question regarding the following statements in the paper:

"Please refer to the supplementary material for more details about modulo edges and experimental validation."
"More details about the dataset creation pipeline can be found in the supplementary material."
"Detailed network architecture can be found in the supplementary material."
"More synthetic results can be found in the supplementary material."
"More real RGB results can be found in the supplementary material."
"Please refer to the supplementary material for how we use SpiCam-Mod to capture modulo images."
"We demonstrate 16-bit HDR reconstruction results in the supplementary material."

Where can I find the supplementary material?

**Comment by fourson** [comment]
Hello there,
The supplementary material can be downloaded from the NeurIPS official website.
Please check the following link:
https://papers.nips.cc/paper_files/paper/2020/hash/1102a326d5f7c9e04fc3c89d0ede88c9-Abstract.html
